# Generated by Django 4.2.16 on 2024-10-09 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0007_post_post_tags'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='post_tags',
            new_name='tags',
        ),
    ]
