# Generated by Django 4.2.16 on 2024-10-01 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_customuser_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='profile_picture',
            field=models.ImageField(blank=True, default='accounts/profile_photos/default_photo.png', upload_to='accounts/profile_photos/'),
        ),
    ]
